import Head from 'next/head'
import styles from '../styles/About.module.css'
import Image from 'next/image'
import profilePic from '../images/Three.jpg'

const About = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Personal Website</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className = {styles.box}>
                    <div className = {styles.firstOne}>
                        <h1>Nishanth Prajith.</h1>
                        <p>Dynamic and reliable Software Developer with a strong work ethic and a passion for developing user-centric products. Ability to function well independently with little to no supervision or in coordination with a professional team. Experienced in a wide array of programming languages, frameworks and content management sites such as Wordpress.</p>
                    </div>
                    <div className = {styles.secondOne}>
                        <div className = {styles.rotatedAbout}>
                            <p style = {{color: "gray"}}>ABOUT</p>
                        </div>
                        <div className = {styles.imageOne}>
                            <Image src={profilePic} alt="Picture of the author"/>
                        </div>
                    </div>
                </div>
                <div className = {styles.box}>
                    <div className = {styles.firstInfo}>
                        <p className = {styles.One}>EDUCATION</p>
                    </div>
                    <div className = {styles.firstData}>
                        <div>
                            <svg width="15" height="15" className = {styles.circleOne}>
                                <circle cx="7.5" cy="7.5" r="5" stroke="#000" strokeWidth="2" fill="#fff" />
                                Sorry, your browser does not support inline SVG.
                            </svg>
                            <div className = {styles.lineOne}>
                                <h4>WEB DESIGN</h4>
                                <p className= {styles.boxYear}>2015 - 2018</p>
                                <p className = {styles.makeItalic}>Thomas A. Edison C.T.E High School, Jamaica, NY</p>
                                <p>I studied web developement and graphic design, specically HTML, CSS, Adobe Photoshop and Illustrator.</p>
                            </div>
                        </div>
                        
                        <div> 
                            <svg width="15" height="15" className = {styles.circleTwo}>
                                <circle cx="7.5" cy="7.5" r="5" stroke="#000" strokeWidth="2" fill="#fff" />
                                Sorry, your browser does not support inline SVG.
                            </svg>
                            <div className = {styles.lineTwo}>
                                <h4>BACHELORS IN COMPUTER SCIENCE</h4>
                                <p className= {styles.boxYear}>2019 - Current</p>
                                <p className = {styles.makeItalic}>City College Of New York, New York City, NY</p>
                                <p>Currently, studying Computer science at the grove school of engineering.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className = {styles.box}>
                    <div className = {styles.firstData}>
                        <div> 
                            <svg width="15" height="15" className = {styles.circleTwoOne}>
                                <circle cx="7.5" cy="7.5" r="5" stroke="#000" strokeWidth="2" fill="#fff" />
                                Sorry, your browser does not support inline SVG.
                            </svg>
                            <div className = {styles.lineTwo}>
                                <h4>WEB DESIGNER</h4>
                                <p className= {styles.boxYear}>2017 - 2018</p>
                                <p className = {styles.makeItalic}>Thomas A. Edison C.T.E High School, Jamaica, NY</p>
                                <p>I maintained the schools website, and updated it with new events and annoucments on a weekly basis.</p>
                            </div>
                        </div>
                    </div>
                    <div className = {styles.firstInfoTwo}>
                        <p className = {styles.Two}>PROFESSIONAL EXPERIENCE</p>
                    </div>
                </div>
                <div style = {{height: "150px"}}>

                </div>
                <div className = {styles.box}>
                    <div className = {styles.firstInfo}>
                        <p className = {styles.One}>CODING</p>
                    </div>
                    <div className = {styles.firstDataProgram}>
                        <div className = {styles.boxYearTwo}>
                            <p>C++</p>
                        </div>
                        <div className = {styles.boxYearTwo}>
                            <p>Java</p>
                        </div>
                        <div className = {styles.boxYearTwo}>
                            <p>SQL</p>
                        </div>
                        <div className = {styles.boxYearTwo}>
                            <p>Flutter / Dart</p>
                        </div>
                        <div className = {styles.boxYearTwo}>
                            <p>HTML, CSS & JavaScript</p>
                        </div>
                    </div>
                </div>
                <br/>
                <br/>
                <br/>
                <br/>
            </main>
        </div>
    );
}

export default About;